### ISSUE TITLE
Додайте wiki сторінку із найменуванням та посиланнями на AliExpress усіх компонетів, що були на воркшопі

### ISSUE THREAD

**Issue by viatsyshyn** [elifTech/Home-KIT#2]

**Comment by rkxtd1** [comment]
@dev1lmini Створи, будь ласка, Wiki сторінку, та додай  туди:
1. Посилання на доку
2. Посилання на список компонентів
https://docs.google.com/spreadsheets/d/1b9Lj0J7ZXCStMl5UTp3f9WG7DjfkufSwxTn0gz2nFno

**Comment by dev1lmini** [comment]
https://s3.eu-central-1.amazonaws.com/eliftech.iot.wiki/index.html
