### ISSUE TITLE
Додати презентацію до WiKi сторінки

### ISSUE THREAD

**Issue by rkxtd1** [elifTech/Home-KIT#3]
@dev1lmini Також, було б добре, додати презентацію до WiKi сторінки
[AWS IoT Smart Home 2.pptx](https://github.com/elifTech/Home-KIT/files/727021/AWS.IoT.Smart.Home.2.pptx)

**Comment by dev1lmini** [comment]
https://s3.eu-central-1.amazonaws.com/eliftech.iot.wiki/index.html
